name = "EulerAngles"
uuid = "754c60e7-4104-4b2f-84f1-902fd791391f"
authors = ["louisponet <louisponet@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "^1"
